# templates/rbac.yaml

{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.kubernetes.namespace }}
  name: {{ .Release.Name }}-role
rules:
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.kubernetes.namespace }}
  name: {{ .Release.Name }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.kubernetes.namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
